### ISSUE TITLE
Ólögleg gildi

### ISSUE THREAD

**Issue by Durtur** [Sykurpabbi/kafari#1]
Ólögleg gildi í skráningu köfunar  - gildi sem eru út fyrir töflurnar eða innihalda bókstafi í stað talna - valda villu.

**Comment by eah8** [comment]
Formið/controllerinn kemur núna með villu ef að gildin eru algjörlega út fyrir töflurnar (460 fyrir tíma og 60 fyrir dýpi held ég?).
Vandamálið er að max dýpi/tími getur verið breytilegt eftir því hvað gildið á hinu er (t.d. er 460 max fyrir tíma fyrir mjög grunnar dýfur en fyrir dýpri dýfur er max tími styttri (vona að þetta sé rétt hjá mér, Símon getur kannski sagt til um þetta...). Af því að það er breytilegt þá er engin (auðveld) leið að höndla það í formi/controller heldur þarf að gera það í TableLookupService

**Comment by Durtur** [comment]
Búinn að leysa þetta. Kemur upp svipað error message ef tableLookup skilar null.
