### ISSUE TITLE
PRÓFUN: ApplicationTest

### ISSUE THREAD

**Issue by Durtur** [Sykurpabbi/kafari#12]
c) Framkvæmið prófanir án þess að þurfa að kalla á þjóninn (server) en á laginu þar fyrir neðan þar sem Spring meðhöndlanr HttpRequest beiðnir og afhendir controllernum þau. Notið @AutoConfigureMockMvc Kallið test klasann ApplicationTest.java

**Comment by eah8** [comment]
búið
