### ISSUE TITLE
Vantar ERROR meðhöndlun við /calculateDecompression

### ISSUE THREAD

**Issue by Sykurpabbi** [Sykurpabbi/kafari#5]
Whitelabel Error Page

This application has no explicit mapping for /error, so you are seeing this as a fallback.

Thu Oct 19 09:15:22 GMT 2017
There was an unexpected error (type=Method Not Allowed, status=405).
Request method 'GET' not supported

**Comment by eah8** [comment]
notandi er núna sendur aftur á login síðu ef hann reynir að skrá nýja dýfu
