### ISSUE TITLE
Hástafir og lágstafir í username eiga ekki að skipta máli

### ISSUE THREAD

**Issue by Sykurpabbi** [Sykurpabbi/kafari#7]
Gulli og gulli eru tvö mismunandi username, virkar ekki að skrá sig inn með gulli ef username er Gulli, þurfum að bera saman bara lowercase eða bara uppercase.

**Comment by eah8** [comment]
Ekki að það skipti miklu máli, en ég er ekki viss um að ég sé sammála þessu.
Lykilorð eru almennt case-sensitive þannig að af hverju ættu usernames ekki að vera það líka?
